# Generated by Django 4.2.3 on 2023-09-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chinese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chinese_icon', models.ImageField(default=None, upload_to='imgs/')),
                ('chinese_name', models.CharField(default=None, max_length=50)),
                ('chinese_price', models.CharField(default=None, max_length=50)),
                ('chinese_des', models.TextField()),
            ],
        ),
    ]
