# Generated by Django 4.2.3 on 2023-09-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Italian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('italian_icon', models.ImageField(default=None, upload_to='imgs/')),
                ('italian_name', models.CharField(default=None, max_length=50)),
                ('italian_price', models.CharField(default=None, max_length=50)),
                ('italian_des', models.TextField()),
            ],
        ),
    ]
