# Generated by Django 4.2.3 on 2023-09-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_italian'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indian_Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_icon', models.ImageField(default=None, upload_to='imgs/')),
                ('street_name', models.CharField(default=None, max_length=50)),
                ('street_price', models.CharField(default=None, max_length=50)),
                ('street_des', models.TextField()),
            ],
        ),
    ]
