# Generated by Django 4.2.3 on 2023-09-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0003_indian_street'),
    ]

    operations = [
        migrations.CreateModel(
            name='North',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('north_icon', models.ImageField(default=None, upload_to='imgs/')),
                ('north_name', models.CharField(default=None, max_length=50)),
                ('north_price', models.CharField(default=None, max_length=50)),
                ('north_des', models.TextField()),
            ],
        ),
    ]
