# Generated by Django 4.2.3 on 2023-09-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0004_north'),
    ]

    operations = [
        migrations.CreateModel(
            name='South',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('south_icon', models.ImageField(default=None, upload_to='imgs/')),
                ('south_name', models.CharField(default=None, max_length=50)),
                ('south_price', models.CharField(default=None, max_length=50)),
                ('south_des', models.TextField()),
            ],
        ),
    ]
