# Generated by Django 4.2.3 on 2023-09-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0005_south'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gujraj_icon', models.ImageField(default=None, upload_to='imgs/')),
                ('gujraj_name', models.CharField(default=None, max_length=50)),
                ('gujraj_price', models.CharField(default=None, max_length=50)),
                ('gujraj_des', models.TextField()),
            ],
        ),
    ]
