# Generated by Django 4.2.3 on 2023-10-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0006_guj'),
    ]

    operations = [
        migrations.AddField(
            model_name='chinese',
            name='chinese_id',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='guj',
            name='gujraj_id',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='indian_street',
            name='street_id',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='italian',
            name='italian_id',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='north',
            name='north_id',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='south',
            name='south_id',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
