# Generated by Django 4.2.3 on 2023-10-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0007_chinese_chinese_id_guj_gujraj_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chinese',
            name='id',
        ),
        migrations.RemoveField(
            model_name='guj',
            name='id',
        ),
        migrations.RemoveField(
            model_name='indian_street',
            name='id',
        ),
        migrations.RemoveField(
            model_name='italian',
            name='id',
        ),
        migrations.RemoveField(
            model_name='north',
            name='id',
        ),
        migrations.RemoveField(
            model_name='south',
            name='id',
        ),
        migrations.AlterField(
            model_name='chinese',
            name='chinese_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='guj',
            name='gujraj_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='indian_street',
            name='street_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='italian',
            name='italian_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='north',
            name='north_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='south',
            name='south_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
