# Generated by Django 4.2.3 on 2023-10-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0008_remove_chinese_id_remove_guj_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chinese',
            name='chinese_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='guj',
            name='gujraj_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='indian_street',
            name='street_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='italian',
            name='italian_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='north',
            name='north_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='south',
            name='south_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
