# Generated by Django 4.2.3 on 2023-10-10 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0011_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
