# Generated by Django 4.2.3 on 2023-11-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0012_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
    ]
