# Generated by Django 5.0 on 2023-12-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0013_custom'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
