# Generated by Django 5.0 on 2023-12-31 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0015_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
