# Generated by Django 5.0 on 2024-01-01 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0016_alter_registration_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
