# Generated by Django 5.0 on 2024-01-16 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0017_delete_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Services.chinese')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Services.user')),
            ],
        ),
    ]
